{"name": "Логин с неверным логином и паролем", "status": "passed", "start": 1719430703944, "stop": 1719430705196, "uuid": "7d4a9319-39f0-4338-b626-34e5525f0836", "historyId": "9b8af275a0ba60da19ded6cab5264975", "testCaseId": "9b8af275a0ba60da19ded6cab5264975", "fullName": "tests.test_login.TestLogin#test_login_invalid_user_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-CENUCRE"}, {"name": "thread", "value": "10612-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}